services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apiprojekampi-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ApiKampi123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "ApiKampi123!" -Q "SELECT 1" -No
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiprojekampi-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ApiProjeKampi;User Id=sa;Password=ApiKampi123!;TrustServerCertificate=true"
    ports:
      - "5048:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqldata: